### ISSUE TITLE
The DateTime represented by the string is out of range

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abotx#11]
From customer...

We get the following exception “The DateTime represented by the string is out of range” (when the expiration date is being parsed as DateTime).
I saw others had the same problem in the following thread: https://github.com/dnauck/Portable.Licensing/issues/26.
I tried to set the date to be 200 years from now just as a try, but then I get an exception that the expiration date not match the signature.

**Comment by sjdirect** [comment]
Created a new nuget package 1.2.48 to fix it. I'm unable to repro but have refactored some code that may be the culprit.

**Comment by net-bet** [comment]
still the same problem. other ideas ?

**Comment by net-bet** [comment]
maybe if you generate us a license for 200 years will help ? that way we'll have no issues with the c# max date...

**Comment by sjdirect** [comment]
Notes: I sent @net-bet  a new license with an expiration of 200 years from now. I will make that the default for all lics in the future to make sure others do not have this issue. 

@net-bet, what os/platform are you using? I'm still unable to repro but want to understand why this fails for so few people but worked fine for so many others.

**Comment by sjdirect** [comment]
Related to this issue... 
https://github.com/dnauck/Portable.Licensing/issues/26

**Comment by net-bet** [comment]
I’m developing on Windows 10, .net framework 4.5….

**Comment by sjdirect** [comment]
Fix was deployed to site now. Any new lics will have this automatically. Any lics generated before now would have to be regenerated upon customers request.
