### ISSUE TITLE
Separate crawlerX's crawl each others sites

### ISSUE THREAD

**Issue by MossP** [sjdirect/abotx#12]
I have a Class with `public static AlwaysOnSiteToCrawlProvider _siteToCrawlProviderX = new AlwaysOnSiteToCrawlProvider();` and a function that sets up a globalCrawlEngine from a singleton. 

If I step through code I can see `globalCrawlEngine.parallelCrawler.CrawlerInstanceCreated` getting called and all of the data is correct, however by the time `PageCrawlCompletedAsync => {}` gets called the SiteBag (CrawlBag) data doesn't match the url that has been crawled.

This tends to only happen after a fresh compile of the project and when two requests are made in relatively quick succession.

Any ideas?

**Comment by sjdirect** [comment]
Can you submit a snippet that shows how/where you are setting the dynamic value and where you expect to get the value back out?

**Comment by MossP** [comment]
Sorry for the delay I wanted to be sure the error wasn't getting triggered elsewhere.

Here's an example of it going awry for me..



```
globalCrawlEngine.parallelCrawler.CrawlerInstanceCreatedAsync += (sender, e) =>
{
    e.Crawler.PageCrawlStartingAsync += ProcessPageCrawlStarting;
    e.Crawler.PageCrawlCompletedAsync += ProcessPageCrawlCompleted;
    e.Crawler.PageCrawlDisallowedAsync += PageCrawlDisallowed;
    e.Crawler.PageLinksCrawlDisallowedAsync += PageLinksCrawlDisallowed;

    e.Crawler.CrawlBag.siteID = e.SiteToCrawl.SiteBag.siteID;
    e.Crawler.CrawlBag.siteGrabID = e.SiteToCrawl.SiteBag.siteGrabID;

    var testID1 = e.Crawler.CrawlBag.siteID;
    var testUri1 = e.SiteToCrawl.Uri.AbsoluteUri;
}
```

The variables all match up here. I can add a break point and see that the URL matches the id that has been passed in. But then later in code when the `PageCrawlStartingAsync` event is triggered the variables no longer match.


```
public void ProcessPageCrawlStarting(object sender, PageCrawlStartingArgs e)
{
    var testID2 = e.crawlContext.crawlBag.siteID;
    var testUri2 = e.pageToCrawl.Uri.AbsoluteUri;
}
```

Although testID1 and testID2 match (they are generated new for each crawl), I can see a difference in the host in testUri1 and tstUri2.

**Comment by sjdirect** [comment]
Can you try something for me? Subscribe to the non async version and see if that solves your issue.

globalCrawlEngine.parallelCrawler.CrawlerInstanceCreated

instead of 

globalCrawlEngine.parallelCrawler.CrawlerInstanceCreatedAsync

I suspect that maybe the since the initialization of those values is happening async that it may cause a scenario where it may fire the ProcessPageCrawlStarting event when the CrawlerInstanceCreatedAsync event is halfway done completing.

**Comment by MossP** [comment]
Thanks for getting back to me.

OK. I've tried that and that wasn't it. I did find a dirty way around it but then realised that it was inconsistent. It appears that rootUri and originalRootUri are often set to null the first time through the set to the first site's url on the second pass. The crawler always takes this url as it's base url for the crawl and the isInternal check comes back incorrectly. I have overridden this check now and manually check in the decision maker. as well as passing the base url down in the SiteBag so i can manually re-add it during the instanceCreated function. This seems to work but is a very dirty fix and sometimes drops out (different results each test, even from fresh compile). I am about to try an even dirtier fix by adding a delay in the init of the parallel crawler to simply prevent any additions if the singleton crawler has only recently been setup. I'll let you know how I get on and if you have any other ideas, I'm all ears.

**Comment by sjdirect** [comment]
When I try to set this up with your snippets I'm still unable to repro. Could you create a fully runnable example? Ie.. a console app that registers everything and add a condition in the SiteCrawlStarting that detects when they are mismatched so I can add a breakpoint there and wait for the condition to happen?

**Comment by sjdirect** [comment]
Closing this issue since I cannot repro and have not heard from the reporter in almost 2 weeks
