### ISSUE TITLE
custom implementations for IThreadManager doesn't work

### ISSUE THREAD

**Issue by SchwarzChristian** [sjdirect/abotx#18]
Hi,

when using a custom implementation for `IThreadManager`, injected through `AbotX.Poco.ImplementationContainer.ThreadManager`, i get the following exception:

```
2018-06-12 06:04:00,229 [12] FATAL - [AbotLogger] (0) System.InvalidOperationException: Cannot call DoWork() after AbortAll() or Dispose() have been called.
   bei Abot.Util.ThreadManager.DoWork(Action action)
   bei Abot.Crawler.WebCrawler.CrawlSite()
   bei Abot.Crawler.WebCrawler.Crawl(Uri uri, CancellationTokenSource cancellationTokenSource)
```

The exception is thrown when the crawler crawls the second (and following) seeds in the same thread. While stepping through the code, i saw that `Abot.Crawler.WebCrawler` got the thread manager injected through the constructor and disposes it while executing `Abot.Crawler.WebCrawler.Crawl(...)`. When not using a custom thread manager, the default one is constructed in `AbotX.Parallel.WebCrawlerFactory.CreateInstance(SiteToCrawl)` through the `AbotX.Core.ImplementationOverride` constructor for every crawl. When using the implementation override, the instance passed to `AbotX.Poco.ImplementationContainer.ThreadManager` will be reused for every crawl. So, this instance gets disposed after the first crawl and throws the exception above for all following crawls.

**Comment by sjdirect** [comment]
Hmm, I can see why this is problematic in 2 ways. 

1) What you described above
2) Sharing the same thread manager gets dicey when the same instance is used by multiple concurrent crawls which is what happens.

The best workaround would be to create an implementation of the IWebCrawlerFactory that creates an ICrawlerX with a new instance of your IThreadManager impl with every call to CreateInstance(). You can plug in your impl of IWebCrawlerFactory using the ParallelImplementationOverride object's WebCrawlerFactory property [like the example here](https://abotx.org/Learn/ParallelCrawlerEngine).  You can use the existing WebCrawlerFactory.cs as a template.

Leaving this open to address this in a longer term fix.

**Comment by sjdirect** [comment]
I believe the workaround above will have to do for now since the change to make the implementation container instance aware is unlikely to happen.
