### ISSUE TITLE
What happened to some of the properties that were in v1?

### ISSUE THREAD

**Issue by abukres** [sjdirect/abotx#21]
I had a program that used v1 of abotx. When I upgraded to v2, some of the properties are giving errors because they don't exist anymore. What happened to those properties? 

Like IsExternalPageLinksCrawlingEnabled, DownloadableContentTypes, MaxCrawlDepth, IsExternalPageCrawlingEnabled...

**Comment by sjdirect** [comment]
Be sure you are using the namespace AbotX2 vs AbotX and Abot2 vs Abot. Those properties exist in both versions.
