### ISSUE TITLE
If paid feature is enabled, Abotx doesn't do anything and no warning or exception is present

### ISSUE THREAD

**Issue by thenrich2009** [sjdirect/abotx#23]
I copied some code from here and Abotx didn't work. I tried a few things and found out that if I turned off autotuning, it works. There's no warning or exception to tell me that autotuning is a paid feature and I had to find out the hard way.

I suggest making paid features need a license through an exception message so it's very clear from the start.

**Comment by sjdirect** [comment]
Hi,

This should already be the case with the ParallelCrawlerEngine. It should throw an UnauthorizedExcpetion if you use a feature that is beyond the scope of your license. 

The individual CrawlerX instance makes this available also...

`var crawlResult = await crawler.CrawlAsync(new Uri("http://!YOURSITEHERE!.com"));
if(crawlResult.ErrorOccurred)...
if(crawlResult.ErrorException != null)...`
