### ISSUE TITLE
Incompatibility with net5.0

### ISSUE THREAD

**Issue by Sojaner** [sjdirect/abotx#26]
Consider this piece of code from [AbotX readme page](https://github.com/sjdirect/abotx/blob/master/README.md):
```c#
var crawlEngine = new ParallelCrawlerEngine(
                config, 
                new ParallelImplementationOverride(config, 
                    new ParallelImplementationContainer()
                    {
                        SiteToCrawlProvider = siteToCrawlProvider,
                        WebCrawlerFactory = new WebCrawlerFactory(config)//Same config will be used for every crawler
                    })
                ); 
```
It works fine on `netcoreapp3.1`, however on `net5.0`, the line `new ParallelImplementationOverride(config...` raises the exception `System.Security.Cryptography.CryptographicException: ASN1 corrupted data.` originating from `System.Security.Cryptography.Algorithms`. and the execution of the code is fatally interrupted.

This makes it impossible to use the parallel crawler on .net 5.

**Comment by Sojaner** [comment]
@rjones0604 we are exactly at the same edge of buying the license or not, while currently trying the trial.

It will be a great deal to be able to use the library on net5.x.

Hopefully, @sjdirect will have an answer for us sometime soon?

**Comment by sjdirect** [comment]
I have a patch in 2.1.12 that should fix this issue for now. Let me know if that worked for you all.

**Comment by rjones0604** [comment]
The 2.1.12 patch fixed the issue.  We went ahead and purchased the license.  Thank Stephen for fixing this so quickly.

Rob Jones

**Comment by Sojaner** [comment]
Thanks @sjdirect.
