### ISSUE TITLE
Crawl through a proxy server

### ISSUE THREAD

**Issue by Sojaner** [sjdirect/abotx#29]
Hi,

I'm trying to figure out how to configure the crawler to use a proxy serve/port for connecting to the destination website, but I don't seem to be able to find any information for that.

Is there any way of doing that?

**Comment by sjdirect** [comment]
See [this forum post](https://groups.google.com/g/abot-web-crawler/c/aD6Q5L8zYxE/m/NqDBJWAOhzsJ). Also, that is a better place to ask questions.

**Comment by Sojaner** [comment]
Thanks for the quick reply. Sorry, I was not aware of the forum.
