### ISSUE TITLE
Text issue on abotx.org website

### ISSUE THREAD

**Issue by dcasso** [sjdirect/abotx#3]
In the example it uses :
crawler.CrawlConfigurationX.IsJavascriptRenderingEnabled = true;
crawler.CrawlConfigurationX.MaxConcurrentSiteCrawls = 1;     //Only crawl a single site at a time
crawler.CrawlConfigurationX.MaxConcurrentThreads = 8;    

Instead of the CrawlConfigurationX class.

**Comment by sjdirect** [comment]
Thanks, Will update the docs. Should be this...

var config = new CrawlConfigurationX
{
	IsJavascriptRenderingEnabled = true;
	MaxConcurrentSiteCrawls = 1;     //Only crawl a single site at a time
	MaxConcurrentThreads = 8;         //Logical processor count to avoid cpu thrashing
}
var crawler = new CrawlerX(config);

//Add optional decision whether javascript should be rendered
crawler.ShouldRenderPageJavascript((crawledPage, crawlContext) =>
{
    if(crawledPage.Uri.AbsoluteUri.Contains("ghost"))
        return new CrawlDecision {Allow = false, Reason = "scared to render ghost javascript"};

    return new CrawlDecision { Allow = true };
});
var crawlerTask = crawler.CrawlAsync(new Uri("http://blahblahblah.com"));

**Comment by dcasso** [comment]
It doesn't take many seconds to figure out what to do.

Is it too small a "bug" to post?

**Comment by sjdirect** [comment]
Not at all. Glad you posted it. [Example has been corrected](https://abotx.org/Learn/JavascriptRendering). Thanks!
