### ISSUE TITLE
Releasing the source code for Abotx

### ISSUE THREAD

**Issue by Tony20221** [sjdirect/abotx#35]
Abotx.org website doesn't exist anymore. 
If the author has no more monetization interest in abotx and providing support, how about releasing its source code?

**Comment by sjdirect** [comment]
Apologize for the lack of movement in Abot/Abotx for the last few years. I've been an active leader in one of the greatest tech comebacks in history at Carvana which hasn't left much time for my passion projects. I'm about to take a hiatus and likely get back to active development on these two libraries (among other exciting projects). Stay tuned...
