### ISSUE TITLE
AbotX.lic

### ISSUE THREAD

**Issue by dcasso** [sjdirect/abotx#4]
The beta license file for Abotx.lic does not seem to allow me to use the javascript rendering.

[2016-02-17 21:01:09,557] [6] [FATAL] - System.UnauthorizedAccessException: Your current AbotX license does not include rendering of javascript. Please change IsJavascriptRenderingEnabled to false or upgrade your license.
   at AbotX.Core.PhantomJsRenderer.IsLicensed()

But I have placed the lic file in the bin directory.
![image](https://cloud.githubusercontent.com/assets/898458/13122991/1edb2348-d5ba-11e5-99ca-5fbbe12d649d.png)

**Comment by sjdirect** [comment]
Followed the installation instructions and created a console app with the beta lic and the javascript example. It runs fine. See if you can run it.

[ConsoleApplication1.zip](https://github.com/sjdirect/abotx/files/135089/ConsoleApplication1.zip)

**Comment by dcasso** [comment]
Yes, you are right :) works fine in the console app you made.

I am trying to get it to work in a web app and since I couldn't get that to work, I was sure it was related to the beta license.

**Comment by Dmmaj7** [comment]
I installed the Abotx through NuGet, but there was no AbotX.lic file in my directory and got a error saying "Your current AbotX license does not include rendering of javascript. Please change IsJavascriptRenderingEnabled to false or upgrade your license" when my programm was running. And I downloaded the ConsoleApplication1.zip and it couldn't run for the same error. Is there any solution?Thanks:)

**Comment by sjdirect** [comment]
Hello,

The nuget package does not install any license file. By having no license
file it AbotX defaults to the free Basic edition. If you would like to use
features from Professional or Ultimate edition you would either need to
register for the trial or pay for that edition. You can do all of those here
<https://abotx.org/Buy/Pricing>.

Hope that helps

**Comment by Dmmaj7** [comment]
Thanks for your reply.I just found the pricing page yesterday afternoon,then registered the trial license and I did it several times.But I got nothing received so far.

**Comment by sjdirect** [comment]
Maybe in spam folder? Can you send an email to support@abotx.org with the
email address that was used to register? I will be able to manually send
you your trial information. Sorry you are having trouble.
